language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install -e ".[test]"
  - python -m pip install flake8 flake8-ets
script:
  - python -m flake8
  - python -m unittest discover -v ibm2ieee
