name: Run tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        python-architecture: [x86, x64]
        exclude:
        - os: macos-latest
          python-architecture: x86
        - os: ubuntu-latest
          python-architecture: x86

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the commit
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.python-architecture }})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture }}
        cache: 'pip'
        cache-dependency-path: '.github/workflows/test-requirements.txt'
    - name: Install prerequisites
      run: python -m pip install -r .github/workflows/test-requirements.txt
    - name: Install the package
      run: python -m pip install .
    - name: Run style checks
      run: |
        python -m isort --check .
        python -m black --check .
        python -m flake8
    - name: Run tests from a clean directory
      run: |
        mkdir testdir
        cd testdir
        python -m unittest discover -v ibm2ieee
