name: Run tests

on:
  pull_request

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        python-architecture: [x86, x64]
        exclude:
        - os: macos-latest
          python-architecture: x86
        - os: ubuntu-latest
          python-architecture: x86

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the commit
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.python-architecture }})
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture }}
    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel
        python -m pip install flake8 flake8-ets
        python -m pip install .
    - name: Run style check
      run: |
        python -m flake8
    - name: Run tests
      run: |
        mkdir testdir
        cd testdir
        python -m unittest discover -v ibm2ieee
